version: '3.6'

services:
    nginx:
        container_name: devom-nginx
        image: nginx:1.15-alpine
        restart: unless-stopped
        expose:
            - '80'
        ports:
            - "8030:80"
        networks:
            - devom
        volumes:
            - ../:/app:delegated
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php

    php:
        container_name: devom-php
        image: php-fpm-devom
        build:
            context: ../
            dockerfile: local/Dockerfile
        restart: unless-stopped
        expose:
            - '9000'
        ports:
            - "9030:9001"
        networks:
            - devom
        volumes:
            - ../:/app:delegated
        env_file:
            - ../.env
        depends_on:
            - pgsql
#            - rabbitmq

    pgsql:
        container_name: devom-pgsql
        image: postgres
        restart: unless-stopped
        ports:
            - 5432:5432
        networks:
            - devom
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ../var:/var/lib/postgresql/data

#    rabbitmq:
#        container_name: devom-rabbitmq
#        image: 'rabbitmq:3.7-management'
#        restart: unless-stopped
#        ports:
#            - 5630:5672
#            - 15630:15672
#        env_file:
#            - ../.env

volumes:
    db-data:
        driver: local

networks:
    devom:
        #external: true
        name: devom_net
