#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api:
    resource: '../../../../../../src/Appto/**/Infrastructure/Api/**/*Controller.php'
    type: annotation
#    host: '%router.request_context.host%'
    prefix: api/v1/
    options:
        i18n: false
    defaults:
        _format: 'json'
